repositories:
- name: incubator
  url: https://charts.helm.sh/incubator 
releases:
- name: create-pv
  chart: incubator/raw
  version: 0.2.3
  createNamespace: false
  wait: true
  values:
  - values-template-pv.yaml
