apiVersion: v1
kind: Service
metadata:
  name: {{ include "webpyapp.fullname" . }}
  labels:
    {{- include "webpyapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "webpyapp.selectorLabels" . | nindent 4 }}
