apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-delay-after
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: update-app
        image: bash
        command: ["sh",  "-c", "sleep 60"]
      restartPolicy: Never
  backoffLimit: 4